# Generated by Django 3.2 on 2021-06-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
                ('discription', models.CharField(max_length=1000)),
                ('url_images', models.CharField(max_length=1000)),
                ('taitle', models.CharField(max_length=1000)),
                ('status', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.categories')),
            ],
        ),
    ]
