# Generated by Django 3.2 on 2021-08-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210627_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('item', models.TextField()),
            ],
        ),
    ]
