# Generated by Django 3.2 on 2021-08-25 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
